-- PR7 provisional infrastructure fix: resync public.official_program_notions
-- with the canonical taxonomy in src/data/program/official-program-v2.json.
--
-- Root cause: the table was seeded once in 20260810000100_pr7_question_bank.sql
-- with 4 placeholder rows (NUM-F01..NUM-F04, an early scaffold taxonomy) and was
-- never updated when the real taxonomy grew to 82 notions / 14 chapters / 8
-- parts (see commit dac6b9b "feat: integrate complete 1765-generator Quiz TSI
-- bank"). Any official classification outside those 4 placeholder rows -
-- including INT-F02 - was unconditionally rejected by
-- import_chatgpt_question_drafts() as "classification-unresolved", regardless
-- of the chapterId/notionId sent.
--
-- This migration only replaces the table's content. It does not touch the
-- resolver function, RLS policies, or any other schema object.
--
-- Regenerate this block with:
--   node scripts/generate-official-program-notions-sql.mjs

-- Generated by scripts/generate-official-program-notions-sql.mjs
-- Source: src/data/program/official-program-v2.json (82 notions)
-- Do not edit by hand: re-run the script and paste the output into a new migration.
delete from public.official_program_notions;
insert into public.official_program_notions (notion_id, chapter_id, part_id, chapter_label, notion_label) values
  ('ALG-F01','algebraic-calculus','fundamentals','Calcul algébrique','Développement et réduction d’expressions'),
  ('ALG-F02','algebraic-calculus','fundamentals','Calcul algébrique','Développement par identités remarquables de degrés 2 et 3'),
  ('ALG-F03','algebraic-calculus','fundamentals','Calcul algébrique','Factorisation par facteur commun et regroupement'),
  ('ALG-F04','algebraic-calculus','fundamentals','Calcul algébrique','Factorisation par identités remarquables'),
  ('ALG-F05','algebraic-calculus','fundamentals','Calcul algébrique','Mise au même dénominateur et addition de fractions rationnelles'),
  ('ALG-F06','algebraic-calculus','fundamentals','Calcul algébrique','Simplification et décomposition simple de fractions rationnelles'),
  ('ALGO-F01','algorithms-python','algorithms','Algorithmique et Python','Conditions et branchements'),
  ('ALGO-F02','algorithms-python','algorithms','Algorithmique et Python','Boucles bornées et boucles imbriquées'),
  ('ALGO-F03','algorithms-python','algorithms','Algorithmique et Python','Boucles conditionnelles while et condition d’arrêt'),
  ('ALGO-F04','algorithms-python','algorithms','Algorithmique et Python','Accumulateurs, produits et compteurs'),
  ('ALGO-F05','algorithms-python','algorithms','Algorithmique et Python','Manipulation de listes'),
  ('ALGO-F06','algorithms-python','algorithms','Algorithmique et Python','Simulation aléatoire et fréquences'),
  ('ALGO-F07','algorithms-python','algorithms','Algorithmique et Python','Fonctions Python : paramètres, retour et portée locale'),
  ('ANA-F01','analysis-logarithms-exponentials','functions-analysis','Analyse, logarithmes et exponentielles','Calculs avec logarithmes et domaine'),
  ('ANA-F02','analysis-logarithms-exponentials','functions-analysis','Analyse, logarithmes et exponentielles','Calculs exponentiels et lien exponentielle-logarithme'),
  ('ANA-F03','analysis-logarithms-exponentials','functions-analysis','Analyse, logarithmes et exponentielles','Limites de polynômes et fractions rationnelles'),
  ('ANA-F04','analysis-logarithms-exponentials','functions-analysis','Analyse, logarithmes et exponentielles','Limites avec logarithmes, exponentielles et croissances comparées'),
  ('ANA-F05','analysis-logarithms-exponentials','functions-analysis','Analyse, logarithmes et exponentielles','Équations différentielles linéaires du premier ordre à coefficients constants'),
  ('ANA-F06','analysis-logarithms-exponentials','functions-analysis','Analyse, logarithmes et exponentielles','Équations différentielles du second ordre réductibles par z=y’'),
  ('CPL-F01','complex-numbers','complex-numbers','Nombres complexes','Calcul algébrique, conjugaison et quotient'),
  ('CPL-F02','complex-numbers','complex-numbers','Nombres complexes','Module, argument et conversion de formes'),
  ('CPL-F03','complex-numbers','complex-numbers','Nombres complexes','Produits, quotients et puissances en forme exponentielle'),
  ('DER-F01','derivatives-function-study','functions-analysis','Dérivation et étude de fonctions','Dérivées usuelles et combinaisons linéaires'),
  ('DER-F02','derivatives-function-study','functions-analysis','Dérivation et étude de fonctions','Dérivée d’un produit'),
  ('DER-F03','derivatives-function-study','functions-analysis','Dérivation et étude de fonctions','Dérivée d’un quotient'),
  ('DER-F04','derivatives-function-study','functions-analysis','Dérivation et étude de fonctions','Dérivée d’une fonction composée'),
  ('DER-F05','derivatives-function-study','functions-analysis','Dérivation et étude de fonctions','Équation d’une tangente en une abscisse donnée'),
  ('DER-F06','derivatives-function-study','functions-analysis','Dérivation et étude de fonctions','Approximation affine locale'),
  ('DER-F07','derivatives-function-study','functions-analysis','Dérivation et étude de fonctions','Tangentes de pente imposée'),
  ('DER-F08','derivatives-function-study','functions-analysis','Dérivation et étude de fonctions','Tableau de variations et extremums'),
  ('EQI-F01','equations-signs-inequalities','fundamentals','Équations, signes et inéquations','Équations factorisables et produit nul dans R'),
  ('EQI-F02','equations-signs-inequalities','fundamentals','Équations, signes et inéquations','Racines réelles et factorisation réelle d’un trinôme'),
  ('EQI-F03','equations-signs-inequalities','fundamentals','Équations, signes et inéquations','Signe d’un trinôme réel'),
  ('EQI-F04','equations-signs-inequalities','fundamentals','Équations, signes et inéquations','Signe d’un produit ou quotient factorisé'),
  ('EQI-F05','equations-signs-inequalities','fundamentals','Équations, signes et inéquations','Inéquations polynomiales et rationnelles'),
  ('EQI-F06','equations-signs-inequalities','fundamentals','Équations, signes et inéquations','Systèmes d’inéquations et intersections'),
  ('FON-F01','reference-functions-domains','functions-analysis','Fonctions de référence et domaines','Ensemble de définition d’une expression fonctionnelle'),
  ('FON-F02','reference-functions-domains','functions-analysis','Fonctions de référence et domaines','Images et comparaisons par fonctions de référence'),
  ('FON-F03','reference-functions-domains','functions-analysis','Fonctions de référence et domaines','Valeur absolue : calcul, équations et inéquations'),
  ('FON-F04','reference-functions-domains','functions-analysis','Fonctions de référence et domaines','Test calculatoire de parité ou d’imparité'),
  ('FON-F05','reference-functions-domains','functions-analysis','Fonctions de référence et domaines','Composition et décomposition de fonctions'),
  ('GEO-F01','analytic-geometry','geometry-measurements','Géométrie analytique','Coordonnées de vecteurs, milieux et centre de gravité'),
  ('GEO-F02','analytic-geometry','geometry-measurements','Géométrie analytique','Distances entre points dans un repère orthonormé'),
  ('GEO-F03','analytic-geometry','geometry-measurements','Géométrie analytique','Norme, produit scalaire, orthogonalité et centres par perpendicularité'),
  ('GEO-F04','analytic-geometry','geometry-measurements','Géométrie analytique','Angles, longueurs et formule d’Al-Kashi'),
  ('GEO-F05','analytic-geometry','geometry-measurements','Géométrie analytique','Déterminant, colinéarité, alignement, parallélisme et quadrilatères'),
  ('INT-F01','primitives-integrals','functions-analysis','Primitives et intégrales','Primitives usuelles, combinaisons linéaires et condition initiale'),
  ('INT-F02','primitives-integrals','functions-analysis','Primitives et intégrales','Primitives par composition et condition initiale'),
  ('INT-F03','primitives-integrals','functions-analysis','Primitives et intégrales','Intégrales définies, Chasles et comparaison'),
  ('INT-F04','primitives-integrals','functions-analysis','Primitives et intégrales','Aire algébrique, aire géométrique et valeur moyenne'),
  ('MES-F01','euclidean-geometry-measurements','geometry-measurements','Géométrie euclidienne et mesures','Périmètres et aires de figures planes, cercle inclus'),
  ('MES-F02','euclidean-geometry-measurements','geometry-measurements','Géométrie euclidienne et mesures','Volumes de prismes, cylindres, pyramides et cônes'),
  ('MES-F03','euclidean-geometry-measurements','geometry-measurements','Géométrie euclidienne et mesures','Surface et volume d’une sphère'),
  ('MES-F04','euclidean-geometry-measurements','geometry-measurements','Géométrie euclidienne et mesures','Angles, classification et existence d’un triangle'),
  ('MES-F05','euclidean-geometry-measurements','geometry-measurements','Géométrie euclidienne et mesures','Théorème de Pythagore et réciproque'),
  ('MES-F06','euclidean-geometry-measurements','geometry-measurements','Géométrie euclidienne et mesures','Trigonométrie dans le triangle rectangle'),
  ('MES-F07','euclidean-geometry-measurements','geometry-measurements','Géométrie euclidienne et mesures','Triangles égaux et triangles semblables'),
  ('NUM-F01','numbers-arithmetic','fundamentals','Nombres et arithmétique','Calcul d’une expression puis classement dans les ensembles de nombres'),
  ('NUM-F02','numbers-arithmetic','fundamentals','Nombres et arithmétique','Divisibilité, parité, multiples et décomposition première'),
  ('NUM-F03','numbers-arithmetic','fundamentals','Nombres et arithmétique','Lois des puissances à base commune'),
  ('NUM-F04','numbers-arithmetic','fundamentals','Nombres et arithmétique','Simplification d’expressions à puissances, racines et substitutions'),
  ('PRO-F01','probabilities-statistics','probabilities-statistics','Probabilités et statistiques','Équiprobabilité, contraire, union et intersection'),
  ('PRO-F02','probabilities-statistics','probabilities-statistics','Probabilités et statistiques','Probabilité conditionnelle'),
  ('PRO-F03','probabilities-statistics','probabilities-statistics','Probabilités et statistiques','Indépendance de deux événements'),
  ('PRO-F04','probabilities-statistics','probabilities-statistics','Probabilités et statistiques','Arbres pondérés et formule des probabilités totales'),
  ('PRO-F05','probabilities-statistics','probabilities-statistics','Probabilités et statistiques','Loi d’une variable aléatoire discrète et probabilités cumulées'),
  ('PRO-F06','probabilities-statistics','probabilities-statistics','Probabilités et statistiques','Espérance et transformation affine d’une variable'),
  ('PRO-F07','probabilities-statistics','probabilities-statistics','Probabilités et statistiques','Coefficients binomiaux et relation de Pascal'),
  ('PRO-F08','probabilities-statistics','probabilities-statistics','Probabilités et statistiques','Probabilités d’une loi binomiale'),
  ('PRO-F09','probabilities-statistics','probabilities-statistics','Probabilités et statistiques','Moyenne pondérée, variance et écart type d’une série'),
  ('PRO-F10','probabilities-statistics','probabilities-statistics','Probabilités et statistiques','Statistiques à deux variables, ajustement affine et linéarisation'),
  ('SUI-F01','sequences','sequences','Suites numériques','Reconnaissance calculée d’une suite arithmétique, géométrique ou autre'),
  ('SUI-F02','sequences','sequences','Suites numériques','Conversion entre récurrence, forme explicite et rang'),
  ('SUI-F03','sequences','sequences','Suites numériques','Sens de variation d’une suite'),
  ('SUI-F04','sequences','sequences','Suites numériques','Termes, nombre de termes et sommes arithmétiques'),
  ('SUI-F05','sequences','sequences','Suites numériques','Termes, nombre de termes et sommes géométriques'),
  ('SUI-F06','sequences','sequences','Suites numériques','Moyennes arithmétique et géométrique de réels positifs'),
  ('TRI-F01','trigonometry','trigonometry','Trigonométrie','Réduction d’angles, valeurs exactes et identité fondamentale'),
  ('TRI-F02','trigonometry','trigonometry','Trigonométrie','Équations trigonométriques élémentaires et transformées'),
  ('TRI-F03','trigonometry','trigonometry','Trigonométrie','Formules d’addition, de différence et d’angle double'),
  ('TRI-F04','trigonometry','trigonometry','Trigonométrie','Transformations somme-produit, produit-somme et linéarisation'),
  ('TRI-F05','trigonometry','trigonometry','Trigonométrie','Paramètres et représentation d’une fonction sinusoïdale');
